        int n,i,j,temp,flag=0;
        n=nums.size();
        for(i=n-1;i>=1;i--)
        {
            if(nums[i-1]<nums[i])
            {
                for(j=i;j<n-1;j++)
                {
                    if(nums[j]>nums[i-1] && nums[j+1]<nums[i-1])
                    {
                        temp=nums[j];
                        nums[j]=nums[i-1];
                        nums[i-1]=temp;
                        flag=1;
                        break;
                    }
                }
                if(flag==1)
                    break;
                if(flag==0)
                {
                    temp=nums[n-1];
                    nums[n-1]=nums[i-1];
                    nums[i-1]=temp;
                    flag=1;
                    break;
                }
            }
        }
        if(flag==0)
        {
            for(i=0;i<n/2;i++)
            {
                temp=nums[i];
                nums[i]=nums[n-i-1];
                nums[n-i-1]=temp;
            }
        }
        return;
